server:
  host: 0.0.0.0
  port: 7001
  reload: false

store:
  type: chroma
  collection_name: rag_documents
  persist_directory: ./chroma_db
  batch_size: 100

embedder:
  type: huggingface
  model: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
  device: cpu
  batch_size: 32

chunker:
  default_strategy: adaptive
  strategies:
    adaptive:
      min_length: 100
      max_length: 500
      overlap: 50
      separators:
      - "\n\n"
      - "\n"
      - ". "
      - "! "
      - "? "
    fixed:
      chunk_size: 200
      overlap: 20
    semantic:
      min_chunk_size: 100
      max_chunk_size: 500
      overlap: 50
    sentence:
      sentences_per_chunk: 3
      overlap_sentences: 1
    markdown:
      max_chunk_size: 500
      respect_headers: true

llm:
  provider: gemini
  model: gemini-2.5-flash
  api_key: ${GEMINI_API_KEY}
  temperature: 0.7
  max_tokens: 4000
  timeout: 30

reranker:
  type: bm25
  enabled: true
  k1: 1.2
  b: 0.75

# Simplified retrieval settings
retrieval:
  # Number of documents to retrieve from vector store
  retrieve_k: 30  # How many docs to get from vector store
  # Number of documents after reranking (final context)
  rerank_k: 10     # How many docs to keep after reranking
  # Maximum context size in characters
  max_context_chars: 12000

pipeline:
  query_expansion:
    enabled: false  # Set to false for simpler queries
    expansions: 0
  
ingester:
  max_parallel: 8
  batch_size: 100

cors:
  allow_origins:
  - http://localhost:*
  - http://127.0.0.1:*
  allow_credentials: true
  allow_methods:
  - '*'
  allow_headers:
  - '*'

logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: null
