chat:
  auto_scroll: true
  history_limit: 100
  max_message_length: 10000
documents:
  batch_size: 100
  max_file_size_mb: 50
  supported_formats:
  - pdf
  - md
  - txt
  - json
logging:
  level: INFO
  max_log_lines: 1000
  show_timestamps: true
options:
  auto_load_strategies: true
  show_advanced_params: true
server:
  health_check_interval: 10
  timeout: 30
  url: http://localhost:7001
ui:
  defaults:
    max_documents_display: 1000
    text_preview_length: 200
    top_k: 10
  theme: Fusion
  window:
    height: 900
    title: RAG System - Qt6 Interface
    width: 1400
  font_size: 10
  code_font_size: 10
  auto_scroll: true
